version: "3"

services:
  redis:
    image: "redis:latest"
    expose:
      - 6379
    ports:
      - "6379:6379"

  db:
    image: "postgres:latest"
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - env.local
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: deployment/Dockerfile.tg
    depends_on:
      - redis
      - db
    env_file:
      - env.local
    command:
      - python
      - -u
      - main.py
    volumes:
      - .:/opt:z

  backend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.django
    depends_on:
      - redis
      - db
    volumes:
      - .:/opt:z
    ports:
      - "8000:8000"
    env_file:
      - env.local
    command:
      - python
      - -u
      - manage.py
      - runserver
      - "0.0.0.0:8000"


volumes:
  pgdata: